### ISSUE TITLE
Docs - The text component examples are bugged in chrome

### ISSUE THREAD

**Issue by jonaspetersorensen** [aframevr/aframe#4560]
**Description:**

- A-Frame Version:  `<script src="../../../dist/aframe-master.js"></script>`
- Platform / Device: Windows, Google Chrome Version 81.0.4044.113
- Reproducible Code Snippet or URL:  
  All of the text demos linked in [components/text](https://aframe.io/docs/1.0.0/components/text.html#example)

Error message:
```
Uncaught TypeError: navigator.xr.requestDevice is not a function
    at Object.<anonymous> (device.js:21)
    at Object.173._process (device.js:150)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.176../bind (index.js:6)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.149.../package (index.js:25)
    at s (_prelude.js:1)
    at e (_prelude.js:1)
````

They all work fine in Firefox v75.0 (windows).

My development environment is set up to use the same Chrome version and aframe v1.0.4, and I get no errors there. It is just the demos that throw that error message.

**Comment by dmarcos** [comment]
Those examples are outdated pointing to old versions of A-Frame.

**Comment by dmarcos** [comment]
Examples both work on Chrome and Firefox now. This should not be longer an issue.
