### ISSUE TITLE
Look-controls stops working after enter vr

### ISSUE THREAD

**Issue by azmartone** [aframevr/aframe#3546]
- A-Frame Version: 0.8.2
- Platform / Device: Samsung S7 Chrome 66

Using look-controls component on first load, I am able to swipe to change the y rotation of the camera. After enter vr is called, the rotation doesn't change with swipe anymore. Also when you exit vr the rotation doesn't change. The swipe functionality use to work in 0.7.1, regardless if you were in VR or not.

In look-controls.js, debugging shows that the touchmove handler is still firing, but it seems when you try to set the object3d rotation, it doesn't have any effect. 

https://github.com/aframevr/aframe/blob/429591a7d3034f471ea01c4232246aca0fb90b6b/src/components/look-controls.js#L198

```
    el.object3D.rotation.x = hmdEuler.x + pitchObject.rotation.x;
    el.object3D.rotation.y = hmdEuler.y + yawObject.rotation.y;
    el.object3D.rotation.z = 0;

```

**Comment by dmarcos** [comment]
When using a headset you want to honor the user head rotation or it will cause disconfort. It’s a design decision. What’s your use case? You can try wrapping the camera entity in another entity and write a component to rotate it.

**Comment by machenmusik** [comment]
I believe in previous discussions, the typical use case is to apply an orientation offset, not to entirely override which would cause discomfort; currently three.js does not allow such an offset, which is why the recommendation is to use a wrapping entity for that purpose.

**Comment by azmartone** [comment]
Thanks for your reply @dmarcos. I agree, after entering vr the accelerometer should override any swipe to control the rotation. However, after exiting vr mode, I would imagine that the user regains swipe control, which doesn't seem to be the case.  I believe it is because the camera continues to ignore any programmatic changes to rotation.

In my scenario, I'm allowing x and y rotation through swipe, so the camera wrapper approach causes strange gimbal lock areas.

**Comment by dmarcos** [comment]
The samsung S7 is not daydream compatible so Chrome is using the polyfill code path. I cannot reproduce the problem on the iPhone. exiting VR mode renables touch panning.

**Comment by dmarcos** [comment]
@azmarte look-controls does not implement rotation on x axis. Are you using your own component?

**Comment by azmartone** [comment]
@dmarcos I modified the look-controls component to implement x-axis rotation. But my tests were using the original look-controls component. 

In #3450, @ngokevin mentions "now threejs controls camera rotation in VR mode." Do you know where we can find that code?

**Comment by dmarcos** [comment]
@azmartone My understanding is that your problem is not VR mode but after exiting VR mode. threejs controlling the camera in VR mode should not affect you.

**Comment by cuitingcheng** [comment]
@dmarcos having the same issue on Sumsang S7, Huawei P9, XIaomi 6. look-controls no longer works after exit VR mode(works before entering VR mode). Tested with "Hello World" example on Aframe.io.
Browser Chrome 66.0.3359.158

**Comment by dax72** [comment]
I have the same issue on Samsung S8 ( Chrome 66.0.3359.158) with Aframe 0.8.2.
Accelerometer doesn't work before to enter on VR Mode
Swipe doesn't work after exit VR mode

Everything works with Aframe 0.7.1

**Comment by machenmusik** [comment]
Accelerometer works for me without entering VR on S8 with Samsung Internet, but not Chrome

**Comment by dax72** [comment]
Yes, it works with Samsung Internet but not in Chrome

**Comment by dmarcos** [comment]
If you are loading A-Frame scenes in iFrames you have to adhere to the policies:

https://github.com/immersive-web/cardboard-vr-display#iframes

Probably chrome m65 / m66 have started to enforce it. 

Do the A-Frame examples work? https://aframe.io/aframe/examples/

**Comment by machenmusik** [comment]
Hello world example does not work... did not try the rest

**Comment by dax72** [comment]
it’s the same (http or https)... it’s does not work.
I tried without iframe .
Anyway the accelerometer works when you Enter in VR

**Comment by Mosel3y** [comment]
@dmarcos 

> "When using a headset you want to honor the user head rotation or it will cause disconfort. It’s a design decision"

Could anyone point me to where this is being done in the code?

I'm trying to do swipe controls on mobile with a separate VR mode where device then orientation takes over.

To do this, I'm firstly removing the default look-controls on load, and then adding a different component to handle rotation which only uses touch/drag. (I'm using  removeAttribute, and setAtrribute to remove and add the components).

(I need look-controls on desktop, so I'm only doing the above on mobile)

That works fine initially, but on entering VR on mobile and then returning from VR,  then trying to do the same again as described above, it no longer works - instead the device rotation is controlling the camera rotation as would be expected from the default look-controls even though I've removed them on exit.

[Here is a link if anyone had like to try it](http://eici.grxp.io/pages/testing.php)
I'm trying on S7 Android. This problem only pertains to mobile.

I believe this is some way related to the issue above, but if anyone thinks this would be better posed as a a Stack Overflow question or a separate issue, let me know and I'll remove this and try that.

There's something happening in aframe when the device is returning from VR mode, but I can't find where or what is going on.

**Comment by asandersSAP** [comment]
> @dmarcos
> 
> > "When using a headset you want to honor the user head rotation or it will cause disconfort. It’s a design decision"
> 
> Could anyone point me to where this is being done in the code?
> 
> I'm trying to do swipe controls on mobile with a separate VR mode where device orientation then takes over.
> 
> To do this, I'm firstly removing the default look-controls on load, and then adding a different component to handle rotation which only uses touch/drag. (I'm using removeAttribute, and setAtrribute to remove and add the components).
> 
> (I need look-controls on desktop, so I'm only doing the above on mobile)
> 
> That works fine initially, but on entering VR on mobile and then returning from VR, then trying to do the same again as described above, it no longer works - instead the device rotation is controlling the camera rotation as would be expected from the default look-controls even though I've removed them on exit.
> 
> [Here is a link if anyone had like to try it](http://eici.grxp.io/pages/testing.php)
> I'm trying on S7 Android. This problem only pertains to mobile, I've no problem on desktop.
> 
> I believe this is some way related to the issue above, but if anyone thinks this would be better posed as a a Stack Overflow question or a separate issue, let me know and I'll remove this and try that.
> 
> There's something happening in aframe when the device is returning from VR mode, but I can't find where or what is going on.

I have exactly the same use case and the behaviour is how Mosel3y describes. Still persists with AFrame 0.9.0 and its master in all browsers on my S8, S10, and Iphone 8. I am pretty sure I had the same behaviour on desktop version and solved it By initially removing the look-controls component too. 
But on mobile it does not help. 
Do the webgl dragging with orbit controls works when loading the Site. Then enter VR -> camera switch and look-controls added works fine. 
Exit VR Mode with backbutton-> orbit controls behave like Mosel described.
Did someone find a workaround or can we reopen the discussion?

**Comment by dmarcos** [comment]
@asandersSAP Not sure what your `orbit-control`s do. Does `look-control` work as expected when entering / exiting VR mode? It the answer is yes the problem is in your component. Best is to take `look-controls` and derive your own [`orbit-controls`](https://github.com/aframevr/aframe/blob/master/src/components/look-controls.js) from it.
