### ISSUE TITLE
Audio asset throws `TypeError` when `preload="auto"` is used.

### ISSUE THREAD

**Issue by dsinni** [aframevr/aframe#3774]
**Description:**

Hey, guys. I know you guys are hard at work on `0.9.0`, but this issue has been plaguing some of us for some time and were hoping a fix could be managed in the next release.

Setting an `<audio>` asset within `<a-assets>` with `preload="auto"` (as documented at https://aframe.io/docs/master/components/sound.html#preloading-a-sound-asset) throws the following error:

**Firefox 62.0.2 (Windows):**
```js
TypeError: Argument 1 of BaseAudioContext.decodeAudioData does not implement interface ArrayBuffer.[Learn More] three.js:37939:18 
``` 

**Chrome 69.0.3497.100 (Windows):**
```js
three.js:37941 Uncaught (in promise) TypeError: Failed to execute 'decodeAudioData' on 'BaseAudioContext': parameter 1 is not of type 'ArrayBuffer'.
    at three.js:37941
    at three.js:30404
```

- A-Frame Version: `0.8.2`
- Platform / Device: Reproduced in Firefox and Chrome on Windows 10 (only ones tested)
- Reproducible Code Snippet or URL:

**Code:**
https://glitch.com/edit/#!/aframe-audio-preload-bug

**Demo:**
https://aframe-audio-preload-bug.glitch.me/

I'm not sure if this is more of a `THREE` issue, but this is not working as documented. This makes it difficult to preload audio without maybe resorting to the use of `autoplay` on the audio source. This is not ideal.

Thanks.

**Comment by dsinni** [comment]
This also appears to happen when `autoplay` is set.

**Comment by KaiRo-at** [comment]
This sounds like #2754
